// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct AirPlane_DebugController__char_46_ResetPlane_1c0d4ec9_5375_42c3_afd5_8a9c1180e7ed : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalAirPlane_DebugController__char_46_ResetPlane_1c0d4ec9_5375_42c3_afd5_8a9c1180e7ed;

		public static void Serialize(AirPlane_DebugController__char_46_ResetPlane_1c0d4ec9_5375_42c3_afd5_8a9c1180e7ed commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static AirPlane_DebugController__char_46_ResetPlane_1c0d4ec9_5375_42c3_afd5_8a9c1180e7ed Deserialize(IInProtocolBitStream bitStream)
		{

			return new AirPlane_DebugController__char_46_ResetPlane_1c0d4ec9_5375_42c3_afd5_8a9c1180e7ed
			(
			){};
		}
	}
}
