// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct AirPlane_DebugController__char_46_KillPlane_369f8701_4372_4e48_a006_a9d3b5f7e8d6 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalAirPlane_DebugController__char_46_KillPlane_369f8701_4372_4e48_a006_a9d3b5f7e8d6;

		public static void Serialize(AirPlane_DebugController__char_46_KillPlane_369f8701_4372_4e48_a006_a9d3b5f7e8d6 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static AirPlane_DebugController__char_46_KillPlane_369f8701_4372_4e48_a006_a9d3b5f7e8d6 Deserialize(IInProtocolBitStream bitStream)
		{

			return new AirPlane_DebugController__char_46_KillPlane_369f8701_4372_4e48_a006_a9d3b5f7e8d6
			(
			){};
		}
	}
}
